spring:
  datasource:
    url: jdbc:mysql://121.43.150.228:3306/PMRS
#    url: jdbc:mysql://localhost/PMRS
    username: root
    password: iBeZAQqe6K0M6K2
#    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  neo4j:
    authentication:
      username: neo4j
      password: 7507chyfbjhcdwtc_hku
    uri: bolt://121.43.150.228:7687
  elasticsearch:
    rest:

mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml

server:
  port: 8099

common:
  rate:
    low: 5
    high: 7