spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PMRS
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml

server:
  port: 8089