spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wardrobe
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080