# test-application.yml

spring:
  datasource:
    url: jdbc:mysql://121.43.150.228:3306/PMRS
    #    url: jdbc:mysql://localhost/PMRS
    username: root
    password: iBeZAQqe6K0M6K2
    #    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hihikari:
      max-lifetime: 1200000

mybatis:
  mapper-locations: /Users/jackwu/Project/movierecomment-backend/movie/src/main/resources/mapper/**/*Mapper.xml
