spring:
  datasource:
    url: jdbc:mysql://121.43.150.228:3306/PMRS
    username: root
    password: iBeZAQqe6K0M6K2
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  neo4j:
    authentication:
      username: neo4j
      password: password
    uri:

mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml

# PageHelper plugin
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

server:
  port: 8089